### PR TITLE
Update Do you have an app sec team.md

### PR DESCRIPTION
**Pull request by Ambg05**

### CODE REVIEW

**Comment by DinisCruz** [comment]
Hi, I'm prefer to use AppSec (instead of Application Security)

**Comment by Ambg05** [comment]
Thanks for that. Do you need me to go back in to the file and make that change? I also changed info sec to Information Security--do you prefer if I leave all those phrases in their shorter form?

**Comment by DinisCruz** [comment]
yes can you please make the changes, since you already have a PR (Pull Request) the changes will automatically appear here (i.e. no need to send another PR)

**Comment by DinisCruz** [comment]
Hi, yes I can see both commits on this PR

image

**Pull request merged**
